package net.arver.couponapp.mapper;

import java.util.List;
import net.arver.couponapp.entity.UserCoupon;
import net.arver.couponapp.entity.UserCouponExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserCouponSqlProvider.class, method="countByExample")
    long countByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UserCouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_user_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_user_coupon (id, user_coupon_code, ",
        "pic_url, coupon_id, ",
        "user_id, status, ",
        "order_id, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{userCouponCode,jdbcType=VARCHAR}, ",
        "#{picUrl,jdbcType=VARCHAR}, #{couponId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{orderId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserCouponSqlProvider.class, method="insertSelective")
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_coupon_code", property="userCouponCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic_url", property="picUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserCoupon> selectByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_coupon_code, pic_url, coupon_id, user_id, status, order_id, create_time",
        "from t_user_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_coupon_code", property="userCouponCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic_url", property="picUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update t_user_coupon",
        "set user_coupon_code = #{userCouponCode,jdbcType=VARCHAR},",
          "pic_url = #{picUrl,jdbcType=VARCHAR},",
          "coupon_id = #{couponId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserCoupon record);
}