package net.arver.couponapp.entity;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.achieve_amount
     *
     * @mbg.generated
     */
    private Integer achieveAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.reduce_amount
     *
     * @mbg.generated
     */
    private Integer reduceAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coupon
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.id
     *
     * @return the value of t_coupon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.id
     *
     * @param id the value for t_coupon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.code
     *
     * @return the value of t_coupon.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.code
     *
     * @param code the value for t_coupon.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.pic_url
     *
     * @return the value of t_coupon.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.pic_url
     *
     * @param picUrl the value for t_coupon.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.achieve_amount
     *
     * @return the value of t_coupon.achieve_amount
     *
     * @mbg.generated
     */
    public Integer getAchieveAmount() {
        return achieveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.achieve_amount
     *
     * @param achieveAmount the value for t_coupon.achieve_amount
     *
     * @mbg.generated
     */
    public void setAchieveAmount(Integer achieveAmount) {
        this.achieveAmount = achieveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.reduce_amount
     *
     * @return the value of t_coupon.reduce_amount
     *
     * @mbg.generated
     */
    public Integer getReduceAmount() {
        return reduceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.reduce_amount
     *
     * @param reduceAmount the value for t_coupon.reduce_amount
     *
     * @mbg.generated
     */
    public void setReduceAmount(Integer reduceAmount) {
        this.reduceAmount = reduceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.stock
     *
     * @return the value of t_coupon.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.stock
     *
     * @param stock the value for t_coupon.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.title
     *
     * @return the value of t_coupon.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.title
     *
     * @param title the value for t_coupon.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.status
     *
     * @return the value of t_coupon.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.status
     *
     * @param status the value for t_coupon.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.create_time
     *
     * @return the value of t_coupon.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.create_time
     *
     * @param createTime the value for t_coupon.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", achieveAmount=").append(achieveAmount);
        sb.append(", reduceAmount=").append(reduceAmount);
        sb.append(", stock=").append(stock);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}